[build]
  # Build command
  command = "npm run build:prod"
  
  # Directory to publish (usually dist for Vite projects)
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Production environment variables
  VITE_NODE_ENV = "production"
  VITE_API_URL = "https://api.talksy.tech"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.talksy.tech; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.talksy.tech wss://api.talksy.tech; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment-specific deploy contexts
[context.production]
  command = "npm run build:prod"
  [context.production.environment]
    VITE_NODE_ENV = "production"
    VITE_API_URL = "https://api.talksy.tech"

[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    VITE_NODE_ENV = "development"
    VITE_API_URL = "http://localhost:3000"

[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    VITE_NODE_ENV = "development"
    VITE_API_URL = "http://localhost:3000"

# Functions (if needed for serverless functions)
[functions]
  directory = "netlify/functions"

# Form handling (if using Netlify forms)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
