version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - chatty-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  chatty-network:
    driver: bridge
