version: '3.8'

services:
  # Nginx Reverse Proxy Only
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      - AUTH_SERVICE_IP=${AUTH_SERVICE_IP}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT:-3001}
      - MESSAGE_SERVICE_IP=${MESSAGE_SERVICE_IP}
      - MESSAGE_SERVICE_PORT=${MESSAGE_SERVICE_PORT:-3002}
    restart: unless-stopped
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
