version: '3.8'

services:
  # Auth Service Only
  auth-service:
    build: ./auth-service
    ports:
      - "${AUTH_SERVICE_PORT:-3001}:3001"
    environment:
      - AUTH_SERVICE_PORT=3001
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    restart: unless-stopped
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

